### ISSUE TITLE
turf pipelines

### ISSUE THREAD

**Issue by tmcw** [mapbox/pipeline#1]
/cc @morganherlocker this is the reason why I opened https://github.com/Turfjs/turf/issues/169

![pipeline](https://cloud.githubusercontent.com/assets/32314/5534134/17d33728-8a27-11e4-8021-e7be159ee256.gif)

/cc @yhahn @sgillies + @dnomadb because you've surely thought about this too

I think if we were to strongly define what goes in and out of all turf functions, we could make it possible to build pipelines. Now, I'll freely admit that code-free GIS'ing is a moonshot and there are many ways to fail here, regardless, I think there are some things:
- Declaratively creating GIS pipelines is interesting. It could be how we have a single format for many approaches: run this JSON in your browser to do a pipeline, run it on a server to run that pipeline with lots more data. Run operations in Shapely, Turf, and maybe other backends.
- Declaring strong types & interfaces for turf is worth it anyway, besides Flow types and TypeScript I think starting to create .d.ts files or similar will let us structure documentation in awesome ways.
- There is tons of room to tinker here: this demo was built in ~1.5hrs and could be turbocharged with a few days work

**Comment by tmcw** [comment]
More thought bubbles:
- Breaking tasks into pipelines could make them easier to switch between sync, async, and map/reduce modes, with progress indications where appropriate
- The big challenges is railroad splits and non-map data. I think we can do this.

**Comment by ljbade** [comment]
Love this! I was having similar ideas the other week.

Can't wait to see an integrated data -> processing > gl map UI/pipeline.
